<?php
/////////////////////////////////////////////////////////////////////////////
// Represents a form_eye_mag Collection
//
// Copyright @2018 - 2025 James John McGuire
// All rights reserved.
/////////////////////////////////////////////////////////////////////////////
require_once "Defines.php";
require_once "../Libraries/Utils.php";
require_once "../Libraries/DatabaseLibrary.php";

class form_eye_mag
{
	var	$database;
	var $debug;

	/////////////////////////////////////////////////////////////////////////
	// constructor
	/////////////////////////////////////////////////////////////////////////
	function __construct($database, $debug)
	{
		$this->database	= $database;
		$this->debug = $debug;
	}

	/////////////////////////////////////////////////////////////////////////
	// Delete
	/////////////////////////////////////////////////////////////////////////
	function Delete($id)
	{
		$this->debug->Show(Debug::DEBUG, "form_eye_mag::Delete");

		$query = "DELETE FROM form_eye_mag ".
			"WHERE id = '$id'";

		$result = $this->database->Delete($query);
		$this->debug->Show(Debug::DEBUG, "form_eye_mag::Delete return: $result");

		return $result;
	}

	/////////////////////////////////////////////////////////////////////////
	// GetList
	/////////////////////////////////////////////////////////////////////////
	function GetList($where)
	{
		$sql = "SELECT * FROM form_eye_mag";

		if (!empty($where))
		{
			$sql .= ' '.$where;
		}

		$form_eye_mags = $this->database->GetAll($sql);

		return $form_eye_mags;
	}

	/////////////////////////////////////////////////////////////////////////
	// GetRecord
	/////////////////////////////////////////////////////////////////////////
	function GetRecord($id)
	{
		$sql = "SELECT * FROM form_eye_mag WHERE id = '$id'";

		$form_eye_magRecord = $this->database->GetRow($sql);

		return $form_eye_magRecord;
	}

	/////////////////////////////////////////////////////////////////////////
	// Insert
	/////////////////////////////////////////////////////////////////////////
	function Insert($date, $pid, $user, $groupname, $authorized, $activity, $Narrative, $VISITTYPE, $CC1, $HPI1, $QUALITY1, $TIMING1, $DURATION1, $CONTEXT1, $SEVERITY1, $MODIFY1, $ASSOCIATED1, $LOCATION1, $CHRONIC1, $CHRONIC2, $CHRONIC3, $CC2, $HPI2, $QUALITY2, $TIMING2, $DURATION2, $CONTEXT2, $SEVERITY2, $MODIFY2, $ASSOCIATED2, $LOCATION2, $CC3, $HPI3, $QUALITY3, $TIMING3, $DURATION3, $CONTEXT3, $SEVERITY3, $MODIFY3, $ASSOCIATED3, $LOCATION3, $ROSGENERAL, $ROSHEENT, $ROSCV, $ROSPULM, $ROSGI, $ROSGU, $ROSDERM, $ROSNEURO, $ROSPSYCH, $ROSMUSCULO, $ROSIMMUNO, $ROSENDOCRINE, $alert, $oriented, $confused, $SCODVA, $SCOSVA, $PHODVA, $PHOSVA, $WODVA, $WOSVA, $CTLODVA, $CTLOSVA, $MRODVA, $MROSVA, $SCNEARODVA, $SCNEAROSVA, $WNEARODVA, $WNEAROSVA, $MRNEARODVA, $MRNEAROSVA, $GLAREODVA, $GLAREOSVA, $GLARECOMMENTS, $ARODVA, $AROSVA, $CRODVA, $CROSVA, $CTLODVA1, $CTLOSVA1, $PAMODVA, $PAMOSVA, $LIODVA, $LIOSVA, $NVOCHECKED, $ADDCHECKED, $MRODSPH, $MRODCYL, $MRODAXIS, $MRODPRISM, $MRODBASE, $MRODADD, $MROSSPH, $MROSCYL, $MROSAXIS, $MROSPRISM, $MROSBASE, $MROSADD, $MRODNEARSPHERE, $MRODNEARCYL, $MRODNEARAXIS, $MRODPRISMNEAR, $MRODBASENEAR, $MROSNEARSHPERE, $MROSNEARCYL, $MROSNEARAXIS, $MROSPRISMNEAR, $MROSBASENEAR, $CRODSPH, $CRODCYL, $CRODAXIS, $CROSSPH, $CROSCYL, $CROSAXIS, $CRCOMMENTS, $BALANCED, $DIL_RISKS, $WETTYPE, $ATROPINE, $CYCLOMYDRIL, $TROPICAMIDE, $CYCLOGYL, $NEO25, $ARODSPH, $ARODCYL, $ARODAXIS, $AROSSPH, $AROSCYL, $AROSAXIS, $ARODADD, $AROSADD, $ARNEARODVA, $ARNEAROSVA, $ARODPRISM, $AROSPRISM, $CTLODSPH, $CTLODCYL, $CTLODAXIS, $CTLODBC, $CTLODDIAM, $CTLOSSPH, $CTLOSCYL, $CTLOSAXIS, $CTLOSBC, $CTLOSDIAM, $CTL_COMMENTS, $CTLMANUFACTUREROD, $CTLSUPPLIEROD, $CTLBRANDOD, $CTLMANUFACTUREROS, $CTLSUPPLIEROS, $CTLBRANDOS, $CTLODADD, $CTLOSADD, $ODIOPAP, $OSIOPAP, $ODIOPTPN, $OSIOPTPN, $ODIOPFTN, $OSIOPFTN, $ODIOPPOST, $OSIOPPOST, $ODIOPTARGET, $OSIOPTARGET, $IOPTIME, $IOPPOSTTIME, $AMSLEROD, $AMSLEROS, $ODK1, $ODK2, $ODK2AXIS, $OSK1, $OSK2, $OSK2AXIS, $ODAXIALLENGTH, $OSAXIALLENGTH, $ODACD, $OSACD, $ODW2W, $OSW2W, $ODLT, $OSLT, $ODPDMeasured, $OSPDMeasured, $ACT, $ACT1CCDIST, $ACT2CCDIST, $ACT3CCDIST, $ACT4CCDIST, $ACT5CCDIST, $ACT6CCDIST, $ACT7CCDIST, $ACT8CCDIST, $ACT9CCDIST, $ACT10CCDIST, $ACT11CCDIST, $ACT1SCDIST, $ACT2SCDIST, $ACT3SCDIST, $ACT4SCDIST, $ACT5SCDIST, $ACT6SCDIST, $ACT7SCDIST, $ACT8SCDIST, $ACT9SCDIST, $ACT10SCDIST, $ACT11SCDIST, $ACT1SCNEAR, $ACT2SCNEAR, $ACT3SCNEAR, $ACT4SCNEAR, $ACT5SCNEAR, $ACT6SCNEAR, $ACT7SCNEAR, $ACT8SCNEAR, $ACT9SCNEAR, $ACT10SCNEAR, $ACT11SCNEAR, $ACT1CCNEAR, $ACT2CCNEAR, $ACT3CCNEAR, $ACT4CCNEAR, $ACT5CCNEAR, $ACT6CCNEAR, $ACT7CCNEAR, $ACT8CCNEAR, $ACT9CCNEAR, $ACT10CCNEAR, $ACT11CCNEAR, $ODVF1, $ODVF2, $ODVF3, $ODVF4, $OSVF1, $OSVF2, $OSVF3, $OSVF4, $MOTILITYNORMAL, $MOTILITY_RS, $MOTILITY_RI, $MOTILITY_RR, $MOTILITY_RL, $MOTILITY_LS, $MOTILITY_LI, $MOTILITY_LR, $MOTILITY_LL, $MOTILITY_RRSO, $MOTILITY_RLSO, $MOTILITY_RRIO, $MOTILITY_RLIO, $MOTILITY_LRSO, $MOTILITY_LLSO, $MOTILITY_LRIO, $MOTILITY_LLIO, $STEREOPSIS, $ODNPA, $OSNPA, $VERTFUSAMPS, $DIVERGENCEAMPS, $NPC, $DACCDIST, $DACCNEAR, $CACCDIST, $CACCNEAR, $ODCOLOR, $OSCOLOR, $ODCOINS, $OSCOINS, $ODREDDESAT, $OSREDDESAT, $NEURO_COMMENTS, $RUL, $LUL, $RLL, $LLL, $RBROW, $LBROW, $RMCT, $LMCT, $RADNEXA, $LADNEXA, $RMRD, $LMRD, $RLF, $LLF, $RVFISSURE, $LVFISSURE, $ODHERTEL, $OSHERTEL, $HERTELBASE, $RCAROTID, $LCAROTID, $RTEMPART, $LTEMPART, $RCNV, $LCNV, $RCNVII, $LCNVII, $EXT_COMMENTS, $ODSCHIRMER1, $OSSCHRIMER1, $ODSCHRIMER2, $OSSCHRIMER2, $OSCONJ, $ODCONJ, $ODCORNEA, $OSCORNEA, $ODAC, $OSAC, $ODLENS, $OSLENS, $ODIRIS, $OSIRIS, $ODKTHICKNESS, $OSKTHICKNESS, $ODGONIO, $OSGONIO, $ANTSEG_COMMENTS, $PUPIL_NORMAL, $ODPUPILSIZE1, $ODPUPILSIZE2, $ODPUPILREACTIVITY, $ODAPD, $OSPUPILSIZE1, $OSPUPILSIZE2, $OSPUPILREACTIVITY, $OSAPD, $DIMODPUPILSIZE1, $DIMODPUPILSIZE2, $DIMODPUPILREACTIVITY, $DIMOSPUPILSIZE1, $DIMOSPUPILSIZE2, $DIMOSPUPILREACTIVITY, $PUPIL_COMMENTS, $ODVFCONFRONTATION1, $ODVFCONFRONTATION2, $ODVFCONFRONTATION3, $ODVFCONFRONTATION4, $ODVFCONFRONTATION5, $OSVFCONFRONTATION1, $OSVFCONFRONTATION2, $OSVFCONFRONTATION3, $OSVFCONFRONTATION4, $OSVFCONFRONTATION5, $ODDISC, $OSDISC, $ODCUP, $OSCUP, $ODMACULA, $OSMACULA, $ODVESSELS, $OSVESSELS, $ODPERIPH, $OSPERIPH, $ODCMT, $OSCMT, $RETINA_COMMENTS, $IMP, $PLAN, $Technician, $Doctor, $Resource, $LOCKED, $LOCKEDDATE, $LOCKEDBY, $FINISHED)
	{
		$this->debug->Show(Debug::DEBUG, "form_eye_mag::Insert");

		$sql = "INSERT INTO form_eye_mag (date, pid, user, groupname, authorized, activity, Narrative, VISITTYPE, CC1, HPI1, QUALITY1, TIMING1, DURATION1, CONTEXT1, SEVERITY1, MODIFY1, ASSOCIATED1, LOCATION1, CHRONIC1, CHRONIC2, CHRONIC3, CC2, HPI2, QUALITY2, TIMING2, DURATION2, CONTEXT2, SEVERITY2, MODIFY2, ASSOCIATED2, LOCATION2, CC3, HPI3, QUALITY3, TIMING3, DURATION3, CONTEXT3, SEVERITY3, MODIFY3, ASSOCIATED3, LOCATION3, ROSGENERAL, ROSHEENT, ROSCV, ROSPULM, ROSGI, ROSGU, ROSDERM, ROSNEURO, ROSPSYCH, ROSMUSCULO, ROSIMMUNO, ROSENDOCRINE, alert, oriented, confused, SCODVA, SCOSVA, PHODVA, PHOSVA, WODVA, WOSVA, CTLODVA, CTLOSVA, MRODVA, MROSVA, SCNEARODVA, SCNEAROSVA, WNEARODVA, WNEAROSVA, MRNEARODVA, MRNEAROSVA, GLAREODVA, GLAREOSVA, GLARECOMMENTS, ARODVA, AROSVA, CRODVA, CROSVA, CTLODVA1, CTLOSVA1, PAMODVA, PAMOSVA, LIODVA, LIOSVA, NVOCHECKED, ADDCHECKED, MRODSPH, MRODCYL, MRODAXIS, MRODPRISM, MRODBASE, MRODADD, MROSSPH, MROSCYL, MROSAXIS, MROSPRISM, MROSBASE, MROSADD, MRODNEARSPHERE, MRODNEARCYL, MRODNEARAXIS, MRODPRISMNEAR, MRODBASENEAR, MROSNEARSHPERE, MROSNEARCYL, MROSNEARAXIS, MROSPRISMNEAR, MROSBASENEAR, CRODSPH, CRODCYL, CRODAXIS, CROSSPH, CROSCYL, CROSAXIS, CRCOMMENTS, BALANCED, DIL_RISKS, WETTYPE, ATROPINE, CYCLOMYDRIL, TROPICAMIDE, CYCLOGYL, NEO25, ARODSPH, ARODCYL, ARODAXIS, AROSSPH, AROSCYL, AROSAXIS, ARODADD, AROSADD, ARNEARODVA, ARNEAROSVA, ARODPRISM, AROSPRISM, CTLODSPH, CTLODCYL, CTLODAXIS, CTLODBC, CTLODDIAM, CTLOSSPH, CTLOSCYL, CTLOSAXIS, CTLOSBC, CTLOSDIAM, CTL_COMMENTS, CTLMANUFACTUREROD, CTLSUPPLIEROD, CTLBRANDOD, CTLMANUFACTUREROS, CTLSUPPLIEROS, CTLBRANDOS, CTLODADD, CTLOSADD, ODIOPAP, OSIOPAP, ODIOPTPN, OSIOPTPN, ODIOPFTN, OSIOPFTN, ODIOPPOST, OSIOPPOST, ODIOPTARGET, OSIOPTARGET, IOPTIME, IOPPOSTTIME, AMSLEROD, AMSLEROS, ODK1, ODK2, ODK2AXIS, OSK1, OSK2, OSK2AXIS, ODAXIALLENGTH, OSAXIALLENGTH, ODACD, OSACD, ODW2W, OSW2W, ODLT, OSLT, ODPDMeasured, OSPDMeasured, ACT, ACT1CCDIST, ACT2CCDIST, ACT3CCDIST, ACT4CCDIST, ACT5CCDIST, ACT6CCDIST, ACT7CCDIST, ACT8CCDIST, ACT9CCDIST, ACT10CCDIST, ACT11CCDIST, ACT1SCDIST, ACT2SCDIST, ACT3SCDIST, ACT4SCDIST, ACT5SCDIST, ACT6SCDIST, ACT7SCDIST, ACT8SCDIST, ACT9SCDIST, ACT10SCDIST, ACT11SCDIST, ACT1SCNEAR, ACT2SCNEAR, ACT3SCNEAR, ACT4SCNEAR, ACT5SCNEAR, ACT6SCNEAR, ACT7SCNEAR, ACT8SCNEAR, ACT9SCNEAR, ACT10SCNEAR, ACT11SCNEAR, ACT1CCNEAR, ACT2CCNEAR, ACT3CCNEAR, ACT4CCNEAR, ACT5CCNEAR, ACT6CCNEAR, ACT7CCNEAR, ACT8CCNEAR, ACT9CCNEAR, ACT10CCNEAR, ACT11CCNEAR, ODVF1, ODVF2, ODVF3, ODVF4, OSVF1, OSVF2, OSVF3, OSVF4, MOTILITYNORMAL, MOTILITY_RS, MOTILITY_RI, MOTILITY_RR, MOTILITY_RL, MOTILITY_LS, MOTILITY_LI, MOTILITY_LR, MOTILITY_LL, MOTILITY_RRSO, MOTILITY_RLSO, MOTILITY_RRIO, MOTILITY_RLIO, MOTILITY_LRSO, MOTILITY_LLSO, MOTILITY_LRIO, MOTILITY_LLIO, STEREOPSIS, ODNPA, OSNPA, VERTFUSAMPS, DIVERGENCEAMPS, NPC, DACCDIST, DACCNEAR, CACCDIST, CACCNEAR, ODCOLOR, OSCOLOR, ODCOINS, OSCOINS, ODREDDESAT, OSREDDESAT, NEURO_COMMENTS, RUL, LUL, RLL, LLL, RBROW, LBROW, RMCT, LMCT, RADNEXA, LADNEXA, RMRD, LMRD, RLF, LLF, RVFISSURE, LVFISSURE, ODHERTEL, OSHERTEL, HERTELBASE, RCAROTID, LCAROTID, RTEMPART, LTEMPART, RCNV, LCNV, RCNVII, LCNVII, EXT_COMMENTS, ODSCHIRMER1, OSSCHRIMER1, ODSCHRIMER2, OSSCHRIMER2, OSCONJ, ODCONJ, ODCORNEA, OSCORNEA, ODAC, OSAC, ODLENS, OSLENS, ODIRIS, OSIRIS, ODKTHICKNESS, OSKTHICKNESS, ODGONIO, OSGONIO, ANTSEG_COMMENTS, PUPIL_NORMAL, ODPUPILSIZE1, ODPUPILSIZE2, ODPUPILREACTIVITY, ODAPD, OSPUPILSIZE1, OSPUPILSIZE2, OSPUPILREACTIVITY, OSAPD, DIMODPUPILSIZE1, DIMODPUPILSIZE2, DIMODPUPILREACTIVITY, DIMOSPUPILSIZE1, DIMOSPUPILSIZE2, DIMOSPUPILREACTIVITY, PUPIL_COMMENTS, ODVFCONFRONTATION1, ODVFCONFRONTATION2, ODVFCONFRONTATION3, ODVFCONFRONTATION4, ODVFCONFRONTATION5, OSVFCONFRONTATION1, OSVFCONFRONTATION2, OSVFCONFRONTATION3, OSVFCONFRONTATION4, OSVFCONFRONTATION5, ODDISC, OSDISC, ODCUP, OSCUP, ODMACULA, OSMACULA, ODVESSELS, OSVESSELS, ODPERIPH, OSPERIPH, ODCMT, OSCMT, RETINA_COMMENTS, IMP, PLAN, Technician, Doctor, Resource, LOCKED, LOCKEDDATE, LOCKEDBY, FINISHED)".
			" VALUES ('$date', '" + "'$pid', '" + "'$user', '" + "'$groupname', '" + "'$authorized', '" + "'$activity', '" + "'$Narrative', '" + "'$VISITTYPE', '" + "'$CC1', '" + "'$HPI1', '" + "'$QUALITY1', '" + "'$TIMING1', '" + "'$DURATION1', '" + "'$CONTEXT1', '" + "'$SEVERITY1', '" + "'$MODIFY1', '" + "'$ASSOCIATED1', '" + "'$LOCATION1', '" + "'$CHRONIC1', '" + "'$CHRONIC2', '" + "'$CHRONIC3', '" + "'$CC2', '" + "'$HPI2', '" + "'$QUALITY2', '" + "'$TIMING2', '" + "'$DURATION2', '" + "'$CONTEXT2', '" + "'$SEVERITY2', '" + "'$MODIFY2', '" + "'$ASSOCIATED2', '" + "'$LOCATION2', '" + "'$CC3', '" + "'$HPI3', '" + "'$QUALITY3', '" + "'$TIMING3', '" + "'$DURATION3', '" + "'$CONTEXT3', '" + "'$SEVERITY3', '" + "'$MODIFY3', '" + "'$ASSOCIATED3', '" + "'$LOCATION3', '" + "'$ROSGENERAL', '" + "'$ROSHEENT', '" + "'$ROSCV', '" + "'$ROSPULM', '" + "'$ROSGI', '" + "'$ROSGU', '" + "'$ROSDERM', '" + "'$ROSNEURO', '" + "'$ROSPSYCH', '" + "'$ROSMUSCULO', '" + "'$ROSIMMUNO', '" + "'$ROSENDOCRINE', '" + "'$alert', '" + "'$oriented', '" + "'$confused', '" + "'$SCODVA', '" + "'$SCOSVA', '" + "'$PHODVA', '" + "'$PHOSVA', '" + "'$WODVA', '" + "'$WOSVA', '" + "'$CTLODVA', '" + "'$CTLOSVA', '" + "'$MRODVA', '" + "'$MROSVA', '" + "'$SCNEARODVA', '" + "'$SCNEAROSVA', '" + "'$WNEARODVA', '" + "'$WNEAROSVA', '" + "'$MRNEARODVA', '" + "'$MRNEAROSVA', '" + "'$GLAREODVA', '" + "'$GLAREOSVA', '" + "'$GLARECOMMENTS', '" + "'$ARODVA', '" + "'$AROSVA', '" + "'$CRODVA', '" + "'$CROSVA', '" + "'$CTLODVA1', '" + "'$CTLOSVA1', '" + "'$PAMODVA', '" + "'$PAMOSVA', '" + "'$LIODVA', '" + "'$LIOSVA', '" + "'$NVOCHECKED', '" + "'$ADDCHECKED', '" + "'$MRODSPH', '" + "'$MRODCYL', '" + "'$MRODAXIS', '" + "'$MRODPRISM', '" + "'$MRODBASE', '" + "'$MRODADD', '" + "'$MROSSPH', '" + "'$MROSCYL', '" + "'$MROSAXIS', '" + "'$MROSPRISM', '" + "'$MROSBASE', '" + "'$MROSADD', '" + "'$MRODNEARSPHERE', '" + "'$MRODNEARCYL', '" + "'$MRODNEARAXIS', '" + "'$MRODPRISMNEAR', '" + "'$MRODBASENEAR', '" + "'$MROSNEARSHPERE', '" + "'$MROSNEARCYL', '" + "'$MROSNEARAXIS', '" + "'$MROSPRISMNEAR', '" + "'$MROSBASENEAR', '" + "'$CRODSPH', '" + "'$CRODCYL', '" + "'$CRODAXIS', '" + "'$CROSSPH', '" + "'$CROSCYL', '" + "'$CROSAXIS', '" + "'$CRCOMMENTS', '" + "'$BALANCED', '" + "'$DIL_RISKS', '" + "'$WETTYPE', '" + "'$ATROPINE', '" + "'$CYCLOMYDRIL', '" + "'$TROPICAMIDE', '" + "'$CYCLOGYL', '" + "'$NEO25', '" + "'$ARODSPH', '" + "'$ARODCYL', '" + "'$ARODAXIS', '" + "'$AROSSPH', '" + "'$AROSCYL', '" + "'$AROSAXIS', '" + "'$ARODADD', '" + "'$AROSADD', '" + "'$ARNEARODVA', '" + "'$ARNEAROSVA', '" + "'$ARODPRISM', '" + "'$AROSPRISM', '" + "'$CTLODSPH', '" + "'$CTLODCYL', '" + "'$CTLODAXIS', '" + "'$CTLODBC', '" + "'$CTLODDIAM', '" + "'$CTLOSSPH', '" + "'$CTLOSCYL', '" + "'$CTLOSAXIS', '" + "'$CTLOSBC', '" + "'$CTLOSDIAM', '" + "'$CTL_COMMENTS', '" + "'$CTLMANUFACTUREROD', '" + "'$CTLSUPPLIEROD', '" + "'$CTLBRANDOD', '" + "'$CTLMANUFACTUREROS', '" + "'$CTLSUPPLIEROS', '" + "'$CTLBRANDOS', '" + "'$CTLODADD', '" + "'$CTLOSADD', '" + "'$ODIOPAP', '" + "'$OSIOPAP', '" + "'$ODIOPTPN', '" + "'$OSIOPTPN', '" + "'$ODIOPFTN', '" + "'$OSIOPFTN', '" + "'$ODIOPPOST', '" + "'$OSIOPPOST', '" + "'$ODIOPTARGET', '" + "'$OSIOPTARGET', '" + "'$IOPTIME', '" + "'$IOPPOSTTIME', '" + "'$AMSLEROD', '" + "'$AMSLEROS', '" + "'$ODK1', '" + "'$ODK2', '" + "'$ODK2AXIS', '" + "'$OSK1', '" + "'$OSK2', '" + "'$OSK2AXIS', '" + "'$ODAXIALLENGTH', '" + "'$OSAXIALLENGTH', '" + "'$ODACD', '" + "'$OSACD', '" + "'$ODW2W', '" + "'$OSW2W', '" + "'$ODLT', '" + "'$OSLT', '" + "'$ODPDMeasured', '" + "'$OSPDMeasured', '" + "'$ACT', '" + "'$ACT1CCDIST', '" + "'$ACT2CCDIST', '" + "'$ACT3CCDIST', '" + "'$ACT4CCDIST', '" + "'$ACT5CCDIST', '" + "'$ACT6CCDIST', '" + "'$ACT7CCDIST', '" + "'$ACT8CCDIST', '" + "'$ACT9CCDIST', '" + "'$ACT10CCDIST', '" + "'$ACT11CCDIST', '" + "'$ACT1SCDIST', '" + "'$ACT2SCDIST', '" + "'$ACT3SCDIST', '" + "'$ACT4SCDIST', '" + "'$ACT5SCDIST', '" + "'$ACT6SCDIST', '" + "'$ACT7SCDIST', '" + "'$ACT8SCDIST', '" + "'$ACT9SCDIST', '" + "'$ACT10SCDIST', '" + "'$ACT11SCDIST', '" + "'$ACT1SCNEAR', '" + "'$ACT2SCNEAR', '" + "'$ACT3SCNEAR', '" + "'$ACT4SCNEAR', '" + "'$ACT5SCNEAR', '" + "'$ACT6SCNEAR', '" + "'$ACT7SCNEAR', '" + "'$ACT8SCNEAR', '" + "'$ACT9SCNEAR', '" + "'$ACT10SCNEAR', '" + "'$ACT11SCNEAR', '" + "'$ACT1CCNEAR', '" + "'$ACT2CCNEAR', '" + "'$ACT3CCNEAR', '" + "'$ACT4CCNEAR', '" + "'$ACT5CCNEAR', '" + "'$ACT6CCNEAR', '" + "'$ACT7CCNEAR', '" + "'$ACT8CCNEAR', '" + "'$ACT9CCNEAR', '" + "'$ACT10CCNEAR', '" + "'$ACT11CCNEAR', '" + "'$ODVF1', '" + "'$ODVF2', '" + "'$ODVF3', '" + "'$ODVF4', '" + "'$OSVF1', '" + "'$OSVF2', '" + "'$OSVF3', '" + "'$OSVF4', '" + "'$MOTILITYNORMAL', '" + "'$MOTILITY_RS', '" + "'$MOTILITY_RI', '" + "'$MOTILITY_RR', '" + "'$MOTILITY_RL', '" + "'$MOTILITY_LS', '" + "'$MOTILITY_LI', '" + "'$MOTILITY_LR', '" + "'$MOTILITY_LL', '" + "'$MOTILITY_RRSO', '" + "'$MOTILITY_RLSO', '" + "'$MOTILITY_RRIO', '" + "'$MOTILITY_RLIO', '" + "'$MOTILITY_LRSO', '" + "'$MOTILITY_LLSO', '" + "'$MOTILITY_LRIO', '" + "'$MOTILITY_LLIO', '" + "'$STEREOPSIS', '" + "'$ODNPA', '" + "'$OSNPA', '" + "'$VERTFUSAMPS', '" + "'$DIVERGENCEAMPS', '" + "'$NPC', '" + "'$DACCDIST', '" + "'$DACCNEAR', '" + "'$CACCDIST', '" + "'$CACCNEAR', '" + "'$ODCOLOR', '" + "'$OSCOLOR', '" + "'$ODCOINS', '" + "'$OSCOINS', '" + "'$ODREDDESAT', '" + "'$OSREDDESAT', '" + "'$NEURO_COMMENTS', '" + "'$RUL', '" + "'$LUL', '" + "'$RLL', '" + "'$LLL', '" + "'$RBROW', '" + "'$LBROW', '" + "'$RMCT', '" + "'$LMCT', '" + "'$RADNEXA', '" + "'$LADNEXA', '" + "'$RMRD', '" + "'$LMRD', '" + "'$RLF', '" + "'$LLF', '" + "'$RVFISSURE', '" + "'$LVFISSURE', '" + "'$ODHERTEL', '" + "'$OSHERTEL', '" + "'$HERTELBASE', '" + "'$RCAROTID', '" + "'$LCAROTID', '" + "'$RTEMPART', '" + "'$LTEMPART', '" + "'$RCNV', '" + "'$LCNV', '" + "'$RCNVII', '" + "'$LCNVII', '" + "'$EXT_COMMENTS', '" + "'$ODSCHIRMER1', '" + "'$OSSCHRIMER1', '" + "'$ODSCHRIMER2', '" + "'$OSSCHRIMER2', '" + "'$OSCONJ', '" + "'$ODCONJ', '" + "'$ODCORNEA', '" + "'$OSCORNEA', '" + "'$ODAC', '" + "'$OSAC', '" + "'$ODLENS', '" + "'$OSLENS', '" + "'$ODIRIS', '" + "'$OSIRIS', '" + "'$ODKTHICKNESS', '" + "'$OSKTHICKNESS', '" + "'$ODGONIO', '" + "'$OSGONIO', '" + "'$ANTSEG_COMMENTS', '" + "'$PUPIL_NORMAL', '" + "'$ODPUPILSIZE1', '" + "'$ODPUPILSIZE2', '" + "'$ODPUPILREACTIVITY', '" + "'$ODAPD', '" + "'$OSPUPILSIZE1', '" + "'$OSPUPILSIZE2', '" + "'$OSPUPILREACTIVITY', '" + "'$OSAPD', '" + "'$DIMODPUPILSIZE1', '" + "'$DIMODPUPILSIZE2', '" + "'$DIMODPUPILREACTIVITY', '" + "'$DIMOSPUPILSIZE1', '" + "'$DIMOSPUPILSIZE2', '" + "'$DIMOSPUPILREACTIVITY', '" + "'$PUPIL_COMMENTS', '" + "'$ODVFCONFRONTATION1', '" + "'$ODVFCONFRONTATION2', '" + "'$ODVFCONFRONTATION3', '" + "'$ODVFCONFRONTATION4', '" + "'$ODVFCONFRONTATION5', '" + "'$OSVFCONFRONTATION1', '" + "'$OSVFCONFRONTATION2', '" + "'$OSVFCONFRONTATION3', '" + "'$OSVFCONFRONTATION4', '" + "'$OSVFCONFRONTATION5', '" + "'$ODDISC', '" + "'$OSDISC', '" + "'$ODCUP', '" + "'$OSCUP', '" + "'$ODMACULA', '" + "'$OSMACULA', '" + "'$ODVESSELS', '" + "'$OSVESSELS', '" + "'$ODPERIPH', '" + "'$OSPERIPH', '" + "'$ODCMT', '" + "'$OSCMT', '" + "'$RETINA_COMMENTS', '" + "'$IMP', '" + "'$PLAN', '" + "'$Technician', '" + "'$Doctor', '" + "'$Resource', '" + "'$LOCKED', '" + "'$LOCKEDDATE', '" + "'$LOCKEDBY', '" + "'$FINISHED')";

		$result	= $this->database->Insert($sql);
		$this->debug->Show(Debug::DEBUG, "form_eye_mag::Insert return: $result");

		return $result;
	}

	/////////////////////////////////////////////////////////////////////////
	// Update
	/////////////////////////////////////////////////////////////////////////
	function Update($id, $date, $pid, $user, $groupname, $authorized, $activity, $Narrative, $VISITTYPE, $CC1, $HPI1, $QUALITY1, $TIMING1, $DURATION1, $CONTEXT1, $SEVERITY1, $MODIFY1, $ASSOCIATED1, $LOCATION1, $CHRONIC1, $CHRONIC2, $CHRONIC3, $CC2, $HPI2, $QUALITY2, $TIMING2, $DURATION2, $CONTEXT2, $SEVERITY2, $MODIFY2, $ASSOCIATED2, $LOCATION2, $CC3, $HPI3, $QUALITY3, $TIMING3, $DURATION3, $CONTEXT3, $SEVERITY3, $MODIFY3, $ASSOCIATED3, $LOCATION3, $ROSGENERAL, $ROSHEENT, $ROSCV, $ROSPULM, $ROSGI, $ROSGU, $ROSDERM, $ROSNEURO, $ROSPSYCH, $ROSMUSCULO, $ROSIMMUNO, $ROSENDOCRINE, $alert, $oriented, $confused, $SCODVA, $SCOSVA, $PHODVA, $PHOSVA, $WODVA, $WOSVA, $CTLODVA, $CTLOSVA, $MRODVA, $MROSVA, $SCNEARODVA, $SCNEAROSVA, $WNEARODVA, $WNEAROSVA, $MRNEARODVA, $MRNEAROSVA, $GLAREODVA, $GLAREOSVA, $GLARECOMMENTS, $ARODVA, $AROSVA, $CRODVA, $CROSVA, $CTLODVA1, $CTLOSVA1, $PAMODVA, $PAMOSVA, $LIODVA, $LIOSVA, $NVOCHECKED, $ADDCHECKED, $MRODSPH, $MRODCYL, $MRODAXIS, $MRODPRISM, $MRODBASE, $MRODADD, $MROSSPH, $MROSCYL, $MROSAXIS, $MROSPRISM, $MROSBASE, $MROSADD, $MRODNEARSPHERE, $MRODNEARCYL, $MRODNEARAXIS, $MRODPRISMNEAR, $MRODBASENEAR, $MROSNEARSHPERE, $MROSNEARCYL, $MROSNEARAXIS, $MROSPRISMNEAR, $MROSBASENEAR, $CRODSPH, $CRODCYL, $CRODAXIS, $CROSSPH, $CROSCYL, $CROSAXIS, $CRCOMMENTS, $BALANCED, $DIL_RISKS, $WETTYPE, $ATROPINE, $CYCLOMYDRIL, $TROPICAMIDE, $CYCLOGYL, $NEO25, $ARODSPH, $ARODCYL, $ARODAXIS, $AROSSPH, $AROSCYL, $AROSAXIS, $ARODADD, $AROSADD, $ARNEARODVA, $ARNEAROSVA, $ARODPRISM, $AROSPRISM, $CTLODSPH, $CTLODCYL, $CTLODAXIS, $CTLODBC, $CTLODDIAM, $CTLOSSPH, $CTLOSCYL, $CTLOSAXIS, $CTLOSBC, $CTLOSDIAM, $CTL_COMMENTS, $CTLMANUFACTUREROD, $CTLSUPPLIEROD, $CTLBRANDOD, $CTLMANUFACTUREROS, $CTLSUPPLIEROS, $CTLBRANDOS, $CTLODADD, $CTLOSADD, $ODIOPAP, $OSIOPAP, $ODIOPTPN, $OSIOPTPN, $ODIOPFTN, $OSIOPFTN, $ODIOPPOST, $OSIOPPOST, $ODIOPTARGET, $OSIOPTARGET, $IOPTIME, $IOPPOSTTIME, $AMSLEROD, $AMSLEROS, $ODK1, $ODK2, $ODK2AXIS, $OSK1, $OSK2, $OSK2AXIS, $ODAXIALLENGTH, $OSAXIALLENGTH, $ODACD, $OSACD, $ODW2W, $OSW2W, $ODLT, $OSLT, $ODPDMeasured, $OSPDMeasured, $ACT, $ACT1CCDIST, $ACT2CCDIST, $ACT3CCDIST, $ACT4CCDIST, $ACT5CCDIST, $ACT6CCDIST, $ACT7CCDIST, $ACT8CCDIST, $ACT9CCDIST, $ACT10CCDIST, $ACT11CCDIST, $ACT1SCDIST, $ACT2SCDIST, $ACT3SCDIST, $ACT4SCDIST, $ACT5SCDIST, $ACT6SCDIST, $ACT7SCDIST, $ACT8SCDIST, $ACT9SCDIST, $ACT10SCDIST, $ACT11SCDIST, $ACT1SCNEAR, $ACT2SCNEAR, $ACT3SCNEAR, $ACT4SCNEAR, $ACT5SCNEAR, $ACT6SCNEAR, $ACT7SCNEAR, $ACT8SCNEAR, $ACT9SCNEAR, $ACT10SCNEAR, $ACT11SCNEAR, $ACT1CCNEAR, $ACT2CCNEAR, $ACT3CCNEAR, $ACT4CCNEAR, $ACT5CCNEAR, $ACT6CCNEAR, $ACT7CCNEAR, $ACT8CCNEAR, $ACT9CCNEAR, $ACT10CCNEAR, $ACT11CCNEAR, $ODVF1, $ODVF2, $ODVF3, $ODVF4, $OSVF1, $OSVF2, $OSVF3, $OSVF4, $MOTILITYNORMAL, $MOTILITY_RS, $MOTILITY_RI, $MOTILITY_RR, $MOTILITY_RL, $MOTILITY_LS, $MOTILITY_LI, $MOTILITY_LR, $MOTILITY_LL, $MOTILITY_RRSO, $MOTILITY_RLSO, $MOTILITY_RRIO, $MOTILITY_RLIO, $MOTILITY_LRSO, $MOTILITY_LLSO, $MOTILITY_LRIO, $MOTILITY_LLIO, $STEREOPSIS, $ODNPA, $OSNPA, $VERTFUSAMPS, $DIVERGENCEAMPS, $NPC, $DACCDIST, $DACCNEAR, $CACCDIST, $CACCNEAR, $ODCOLOR, $OSCOLOR, $ODCOINS, $OSCOINS, $ODREDDESAT, $OSREDDESAT, $NEURO_COMMENTS, $RUL, $LUL, $RLL, $LLL, $RBROW, $LBROW, $RMCT, $LMCT, $RADNEXA, $LADNEXA, $RMRD, $LMRD, $RLF, $LLF, $RVFISSURE, $LVFISSURE, $ODHERTEL, $OSHERTEL, $HERTELBASE, $RCAROTID, $LCAROTID, $RTEMPART, $LTEMPART, $RCNV, $LCNV, $RCNVII, $LCNVII, $EXT_COMMENTS, $ODSCHIRMER1, $OSSCHRIMER1, $ODSCHRIMER2, $OSSCHRIMER2, $OSCONJ, $ODCONJ, $ODCORNEA, $OSCORNEA, $ODAC, $OSAC, $ODLENS, $OSLENS, $ODIRIS, $OSIRIS, $ODKTHICKNESS, $OSKTHICKNESS, $ODGONIO, $OSGONIO, $ANTSEG_COMMENTS, $PUPIL_NORMAL, $ODPUPILSIZE1, $ODPUPILSIZE2, $ODPUPILREACTIVITY, $ODAPD, $OSPUPILSIZE1, $OSPUPILSIZE2, $OSPUPILREACTIVITY, $OSAPD, $DIMODPUPILSIZE1, $DIMODPUPILSIZE2, $DIMODPUPILREACTIVITY, $DIMOSPUPILSIZE1, $DIMOSPUPILSIZE2, $DIMOSPUPILREACTIVITY, $PUPIL_COMMENTS, $ODVFCONFRONTATION1, $ODVFCONFRONTATION2, $ODVFCONFRONTATION3, $ODVFCONFRONTATION4, $ODVFCONFRONTATION5, $OSVFCONFRONTATION1, $OSVFCONFRONTATION2, $OSVFCONFRONTATION3, $OSVFCONFRONTATION4, $OSVFCONFRONTATION5, $ODDISC, $OSDISC, $ODCUP, $OSCUP, $ODMACULA, $OSMACULA, $ODVESSELS, $OSVESSELS, $ODPERIPH, $OSPERIPH, $ODCMT, $OSCMT, $RETINA_COMMENTS, $IMP, $PLAN, $Technician, $Doctor, $Resource, $LOCKED, $LOCKEDDATE, $LOCKEDBY, $FINISHED)
	{
		$this->debug->Show(Debug::DEBUG, "form_eye_mag::Update");

		$sql = "UPDATE form_eye_mag SET ".
				@"date='$date'," + 
				@"pid='$pid'," + 
				@"user='$user'," + 
				@"groupname='$groupname'," + 
				@"authorized='$authorized'," + 
				@"activity='$activity'," + 
				@"Narrative='$Narrative'," + 
				@"VISITTYPE='$VISITTYPE'," + 
				@"CC1='$CC1'," + 
				@"HPI1='$HPI1'," + 
				@"QUALITY1='$QUALITY1'," + 
				@"TIMING1='$TIMING1'," + 
				@"DURATION1='$DURATION1'," + 
				@"CONTEXT1='$CONTEXT1'," + 
				@"SEVERITY1='$SEVERITY1'," + 
				@"MODIFY1='$MODIFY1'," + 
				@"ASSOCIATED1='$ASSOCIATED1'," + 
				@"LOCATION1='$LOCATION1'," + 
				@"CHRONIC1='$CHRONIC1'," + 
				@"CHRONIC2='$CHRONIC2'," + 
				@"CHRONIC3='$CHRONIC3'," + 
				@"CC2='$CC2'," + 
				@"HPI2='$HPI2'," + 
				@"QUALITY2='$QUALITY2'," + 
				@"TIMING2='$TIMING2'," + 
				@"DURATION2='$DURATION2'," + 
				@"CONTEXT2='$CONTEXT2'," + 
				@"SEVERITY2='$SEVERITY2'," + 
				@"MODIFY2='$MODIFY2'," + 
				@"ASSOCIATED2='$ASSOCIATED2'," + 
				@"LOCATION2='$LOCATION2'," + 
				@"CC3='$CC3'," + 
				@"HPI3='$HPI3'," + 
				@"QUALITY3='$QUALITY3'," + 
				@"TIMING3='$TIMING3'," + 
				@"DURATION3='$DURATION3'," + 
				@"CONTEXT3='$CONTEXT3'," + 
				@"SEVERITY3='$SEVERITY3'," + 
				@"MODIFY3='$MODIFY3'," + 
				@"ASSOCIATED3='$ASSOCIATED3'," + 
				@"LOCATION3='$LOCATION3'," + 
				@"ROSGENERAL='$ROSGENERAL'," + 
				@"ROSHEENT='$ROSHEENT'," + 
				@"ROSCV='$ROSCV'," + 
				@"ROSPULM='$ROSPULM'," + 
				@"ROSGI='$ROSGI'," + 
				@"ROSGU='$ROSGU'," + 
				@"ROSDERM='$ROSDERM'," + 
				@"ROSNEURO='$ROSNEURO'," + 
				@"ROSPSYCH='$ROSPSYCH'," + 
				@"ROSMUSCULO='$ROSMUSCULO'," + 
				@"ROSIMMUNO='$ROSIMMUNO'," + 
				@"ROSENDOCRINE='$ROSENDOCRINE'," + 
				@"alert='$alert'," + 
				@"oriented='$oriented'," + 
				@"confused='$confused'," + 
				@"SCODVA='$SCODVA'," + 
				@"SCOSVA='$SCOSVA'," + 
				@"PHODVA='$PHODVA'," + 
				@"PHOSVA='$PHOSVA'," + 
				@"WODVA='$WODVA'," + 
				@"WOSVA='$WOSVA'," + 
				@"CTLODVA='$CTLODVA'," + 
				@"CTLOSVA='$CTLOSVA'," + 
				@"MRODVA='$MRODVA'," + 
				@"MROSVA='$MROSVA'," + 
				@"SCNEARODVA='$SCNEARODVA'," + 
				@"SCNEAROSVA='$SCNEAROSVA'," + 
				@"WNEARODVA='$WNEARODVA'," + 
				@"WNEAROSVA='$WNEAROSVA'," + 
				@"MRNEARODVA='$MRNEARODVA'," + 
				@"MRNEAROSVA='$MRNEAROSVA'," + 
				@"GLAREODVA='$GLAREODVA'," + 
				@"GLAREOSVA='$GLAREOSVA'," + 
				@"GLARECOMMENTS='$GLARECOMMENTS'," + 
				@"ARODVA='$ARODVA'," + 
				@"AROSVA='$AROSVA'," + 
				@"CRODVA='$CRODVA'," + 
				@"CROSVA='$CROSVA'," + 
				@"CTLODVA1='$CTLODVA1'," + 
				@"CTLOSVA1='$CTLOSVA1'," + 
				@"PAMODVA='$PAMODVA'," + 
				@"PAMOSVA='$PAMOSVA'," + 
				@"LIODVA='$LIODVA'," + 
				@"LIOSVA='$LIOSVA'," + 
				@"NVOCHECKED='$NVOCHECKED'," + 
				@"ADDCHECKED='$ADDCHECKED'," + 
				@"MRODSPH='$MRODSPH'," + 
				@"MRODCYL='$MRODCYL'," + 
				@"MRODAXIS='$MRODAXIS'," + 
				@"MRODPRISM='$MRODPRISM'," + 
				@"MRODBASE='$MRODBASE'," + 
				@"MRODADD='$MRODADD'," + 
				@"MROSSPH='$MROSSPH'," + 
				@"MROSCYL='$MROSCYL'," + 
				@"MROSAXIS='$MROSAXIS'," + 
				@"MROSPRISM='$MROSPRISM'," + 
				@"MROSBASE='$MROSBASE'," + 
				@"MROSADD='$MROSADD'," + 
				@"MRODNEARSPHERE='$MRODNEARSPHERE'," + 
				@"MRODNEARCYL='$MRODNEARCYL'," + 
				@"MRODNEARAXIS='$MRODNEARAXIS'," + 
				@"MRODPRISMNEAR='$MRODPRISMNEAR'," + 
				@"MRODBASENEAR='$MRODBASENEAR'," + 
				@"MROSNEARSHPERE='$MROSNEARSHPERE'," + 
				@"MROSNEARCYL='$MROSNEARCYL'," + 
				@"MROSNEARAXIS='$MROSNEARAXIS'," + 
				@"MROSPRISMNEAR='$MROSPRISMNEAR'," + 
				@"MROSBASENEAR='$MROSBASENEAR'," + 
				@"CRODSPH='$CRODSPH'," + 
				@"CRODCYL='$CRODCYL'," + 
				@"CRODAXIS='$CRODAXIS'," + 
				@"CROSSPH='$CROSSPH'," + 
				@"CROSCYL='$CROSCYL'," + 
				@"CROSAXIS='$CROSAXIS'," + 
				@"CRCOMMENTS='$CRCOMMENTS'," + 
				@"BALANCED='$BALANCED'," + 
				@"DIL_RISKS='$DIL_RISKS'," + 
				@"WETTYPE='$WETTYPE'," + 
				@"ATROPINE='$ATROPINE'," + 
				@"CYCLOMYDRIL='$CYCLOMYDRIL'," + 
				@"TROPICAMIDE='$TROPICAMIDE'," + 
				@"CYCLOGYL='$CYCLOGYL'," + 
				@"NEO25='$NEO25'," + 
				@"ARODSPH='$ARODSPH'," + 
				@"ARODCYL='$ARODCYL'," + 
				@"ARODAXIS='$ARODAXIS'," + 
				@"AROSSPH='$AROSSPH'," + 
				@"AROSCYL='$AROSCYL'," + 
				@"AROSAXIS='$AROSAXIS'," + 
				@"ARODADD='$ARODADD'," + 
				@"AROSADD='$AROSADD'," + 
				@"ARNEARODVA='$ARNEARODVA'," + 
				@"ARNEAROSVA='$ARNEAROSVA'," + 
				@"ARODPRISM='$ARODPRISM'," + 
				@"AROSPRISM='$AROSPRISM'," + 
				@"CTLODSPH='$CTLODSPH'," + 
				@"CTLODCYL='$CTLODCYL'," + 
				@"CTLODAXIS='$CTLODAXIS'," + 
				@"CTLODBC='$CTLODBC'," + 
				@"CTLODDIAM='$CTLODDIAM'," + 
				@"CTLOSSPH='$CTLOSSPH'," + 
				@"CTLOSCYL='$CTLOSCYL'," + 
				@"CTLOSAXIS='$CTLOSAXIS'," + 
				@"CTLOSBC='$CTLOSBC'," + 
				@"CTLOSDIAM='$CTLOSDIAM'," + 
				@"CTL_COMMENTS='$CTL_COMMENTS'," + 
				@"CTLMANUFACTUREROD='$CTLMANUFACTUREROD'," + 
				@"CTLSUPPLIEROD='$CTLSUPPLIEROD'," + 
				@"CTLBRANDOD='$CTLBRANDOD'," + 
				@"CTLMANUFACTUREROS='$CTLMANUFACTUREROS'," + 
				@"CTLSUPPLIEROS='$CTLSUPPLIEROS'," + 
				@"CTLBRANDOS='$CTLBRANDOS'," + 
				@"CTLODADD='$CTLODADD'," + 
				@"CTLOSADD='$CTLOSADD'," + 
				@"ODIOPAP='$ODIOPAP'," + 
				@"OSIOPAP='$OSIOPAP'," + 
				@"ODIOPTPN='$ODIOPTPN'," + 
				@"OSIOPTPN='$OSIOPTPN'," + 
				@"ODIOPFTN='$ODIOPFTN'," + 
				@"OSIOPFTN='$OSIOPFTN'," + 
				@"ODIOPPOST='$ODIOPPOST'," + 
				@"OSIOPPOST='$OSIOPPOST'," + 
				@"ODIOPTARGET='$ODIOPTARGET'," + 
				@"OSIOPTARGET='$OSIOPTARGET'," + 
				@"IOPTIME='$IOPTIME'," + 
				@"IOPPOSTTIME='$IOPPOSTTIME'," + 
				@"AMSLEROD='$AMSLEROD'," + 
				@"AMSLEROS='$AMSLEROS'," + 
				@"ODK1='$ODK1'," + 
				@"ODK2='$ODK2'," + 
				@"ODK2AXIS='$ODK2AXIS'," + 
				@"OSK1='$OSK1'," + 
				@"OSK2='$OSK2'," + 
				@"OSK2AXIS='$OSK2AXIS'," + 
				@"ODAXIALLENGTH='$ODAXIALLENGTH'," + 
				@"OSAXIALLENGTH='$OSAXIALLENGTH'," + 
				@"ODACD='$ODACD'," + 
				@"OSACD='$OSACD'," + 
				@"ODW2W='$ODW2W'," + 
				@"OSW2W='$OSW2W'," + 
				@"ODLT='$ODLT'," + 
				@"OSLT='$OSLT'," + 
				@"ODPDMeasured='$ODPDMeasured'," + 
				@"OSPDMeasured='$OSPDMeasured'," + 
				@"ACT='$ACT'," + 
				@"ACT1CCDIST='$ACT1CCDIST'," + 
				@"ACT2CCDIST='$ACT2CCDIST'," + 
				@"ACT3CCDIST='$ACT3CCDIST'," + 
				@"ACT4CCDIST='$ACT4CCDIST'," + 
				@"ACT5CCDIST='$ACT5CCDIST'," + 
				@"ACT6CCDIST='$ACT6CCDIST'," + 
				@"ACT7CCDIST='$ACT7CCDIST'," + 
				@"ACT8CCDIST='$ACT8CCDIST'," + 
				@"ACT9CCDIST='$ACT9CCDIST'," + 
				@"ACT10CCDIST='$ACT10CCDIST'," + 
				@"ACT11CCDIST='$ACT11CCDIST'," + 
				@"ACT1SCDIST='$ACT1SCDIST'," + 
				@"ACT2SCDIST='$ACT2SCDIST'," + 
				@"ACT3SCDIST='$ACT3SCDIST'," + 
				@"ACT4SCDIST='$ACT4SCDIST'," + 
				@"ACT5SCDIST='$ACT5SCDIST'," + 
				@"ACT6SCDIST='$ACT6SCDIST'," + 
				@"ACT7SCDIST='$ACT7SCDIST'," + 
				@"ACT8SCDIST='$ACT8SCDIST'," + 
				@"ACT9SCDIST='$ACT9SCDIST'," + 
				@"ACT10SCDIST='$ACT10SCDIST'," + 
				@"ACT11SCDIST='$ACT11SCDIST'," + 
				@"ACT1SCNEAR='$ACT1SCNEAR'," + 
				@"ACT2SCNEAR='$ACT2SCNEAR'," + 
				@"ACT3SCNEAR='$ACT3SCNEAR'," + 
				@"ACT4SCNEAR='$ACT4SCNEAR'," + 
				@"ACT5SCNEAR='$ACT5SCNEAR'," + 
				@"ACT6SCNEAR='$ACT6SCNEAR'," + 
				@"ACT7SCNEAR='$ACT7SCNEAR'," + 
				@"ACT8SCNEAR='$ACT8SCNEAR'," + 
				@"ACT9SCNEAR='$ACT9SCNEAR'," + 
				@"ACT10SCNEAR='$ACT10SCNEAR'," + 
				@"ACT11SCNEAR='$ACT11SCNEAR'," + 
				@"ACT1CCNEAR='$ACT1CCNEAR'," + 
				@"ACT2CCNEAR='$ACT2CCNEAR'," + 
				@"ACT3CCNEAR='$ACT3CCNEAR'," + 
				@"ACT4CCNEAR='$ACT4CCNEAR'," + 
				@"ACT5CCNEAR='$ACT5CCNEAR'," + 
				@"ACT6CCNEAR='$ACT6CCNEAR'," + 
				@"ACT7CCNEAR='$ACT7CCNEAR'," + 
				@"ACT8CCNEAR='$ACT8CCNEAR'," + 
				@"ACT9CCNEAR='$ACT9CCNEAR'," + 
				@"ACT10CCNEAR='$ACT10CCNEAR'," + 
				@"ACT11CCNEAR='$ACT11CCNEAR'," + 
				@"ODVF1='$ODVF1'," + 
				@"ODVF2='$ODVF2'," + 
				@"ODVF3='$ODVF3'," + 
				@"ODVF4='$ODVF4'," + 
				@"OSVF1='$OSVF1'," + 
				@"OSVF2='$OSVF2'," + 
				@"OSVF3='$OSVF3'," + 
				@"OSVF4='$OSVF4'," + 
				@"MOTILITYNORMAL='$MOTILITYNORMAL'," + 
				@"MOTILITY_RS='$MOTILITY_RS'," + 
				@"MOTILITY_RI='$MOTILITY_RI'," + 
				@"MOTILITY_RR='$MOTILITY_RR'," + 
				@"MOTILITY_RL='$MOTILITY_RL'," + 
				@"MOTILITY_LS='$MOTILITY_LS'," + 
				@"MOTILITY_LI='$MOTILITY_LI'," + 
				@"MOTILITY_LR='$MOTILITY_LR'," + 
				@"MOTILITY_LL='$MOTILITY_LL'," + 
				@"MOTILITY_RRSO='$MOTILITY_RRSO'," + 
				@"MOTILITY_RLSO='$MOTILITY_RLSO'," + 
				@"MOTILITY_RRIO='$MOTILITY_RRIO'," + 
				@"MOTILITY_RLIO='$MOTILITY_RLIO'," + 
				@"MOTILITY_LRSO='$MOTILITY_LRSO'," + 
				@"MOTILITY_LLSO='$MOTILITY_LLSO'," + 
				@"MOTILITY_LRIO='$MOTILITY_LRIO'," + 
				@"MOTILITY_LLIO='$MOTILITY_LLIO'," + 
				@"STEREOPSIS='$STEREOPSIS'," + 
				@"ODNPA='$ODNPA'," + 
				@"OSNPA='$OSNPA'," + 
				@"VERTFUSAMPS='$VERTFUSAMPS'," + 
				@"DIVERGENCEAMPS='$DIVERGENCEAMPS'," + 
				@"NPC='$NPC'," + 
				@"DACCDIST='$DACCDIST'," + 
				@"DACCNEAR='$DACCNEAR'," + 
				@"CACCDIST='$CACCDIST'," + 
				@"CACCNEAR='$CACCNEAR'," + 
				@"ODCOLOR='$ODCOLOR'," + 
				@"OSCOLOR='$OSCOLOR'," + 
				@"ODCOINS='$ODCOINS'," + 
				@"OSCOINS='$OSCOINS'," + 
				@"ODREDDESAT='$ODREDDESAT'," + 
				@"OSREDDESAT='$OSREDDESAT'," + 
				@"NEURO_COMMENTS='$NEURO_COMMENTS'," + 
				@"RUL='$RUL'," + 
				@"LUL='$LUL'," + 
				@"RLL='$RLL'," + 
				@"LLL='$LLL'," + 
				@"RBROW='$RBROW'," + 
				@"LBROW='$LBROW'," + 
				@"RMCT='$RMCT'," + 
				@"LMCT='$LMCT'," + 
				@"RADNEXA='$RADNEXA'," + 
				@"LADNEXA='$LADNEXA'," + 
				@"RMRD='$RMRD'," + 
				@"LMRD='$LMRD'," + 
				@"RLF='$RLF'," + 
				@"LLF='$LLF'," + 
				@"RVFISSURE='$RVFISSURE'," + 
				@"LVFISSURE='$LVFISSURE'," + 
				@"ODHERTEL='$ODHERTEL'," + 
				@"OSHERTEL='$OSHERTEL'," + 
				@"HERTELBASE='$HERTELBASE'," + 
				@"RCAROTID='$RCAROTID'," + 
				@"LCAROTID='$LCAROTID'," + 
				@"RTEMPART='$RTEMPART'," + 
				@"LTEMPART='$LTEMPART'," + 
				@"RCNV='$RCNV'," + 
				@"LCNV='$LCNV'," + 
				@"RCNVII='$RCNVII'," + 
				@"LCNVII='$LCNVII'," + 
				@"EXT_COMMENTS='$EXT_COMMENTS'," + 
				@"ODSCHIRMER1='$ODSCHIRMER1'," + 
				@"OSSCHRIMER1='$OSSCHRIMER1'," + 
				@"ODSCHRIMER2='$ODSCHRIMER2'," + 
				@"OSSCHRIMER2='$OSSCHRIMER2'," + 
				@"OSCONJ='$OSCONJ'," + 
				@"ODCONJ='$ODCONJ'," + 
				@"ODCORNEA='$ODCORNEA'," + 
				@"OSCORNEA='$OSCORNEA'," + 
				@"ODAC='$ODAC'," + 
				@"OSAC='$OSAC'," + 
				@"ODLENS='$ODLENS'," + 
				@"OSLENS='$OSLENS'," + 
				@"ODIRIS='$ODIRIS'," + 
				@"OSIRIS='$OSIRIS'," + 
				@"ODKTHICKNESS='$ODKTHICKNESS'," + 
				@"OSKTHICKNESS='$OSKTHICKNESS'," + 
				@"ODGONIO='$ODGONIO'," + 
				@"OSGONIO='$OSGONIO'," + 
				@"ANTSEG_COMMENTS='$ANTSEG_COMMENTS'," + 
				@"PUPIL_NORMAL='$PUPIL_NORMAL'," + 
				@"ODPUPILSIZE1='$ODPUPILSIZE1'," + 
				@"ODPUPILSIZE2='$ODPUPILSIZE2'," + 
				@"ODPUPILREACTIVITY='$ODPUPILREACTIVITY'," + 
				@"ODAPD='$ODAPD'," + 
				@"OSPUPILSIZE1='$OSPUPILSIZE1'," + 
				@"OSPUPILSIZE2='$OSPUPILSIZE2'," + 
				@"OSPUPILREACTIVITY='$OSPUPILREACTIVITY'," + 
				@"OSAPD='$OSAPD'," + 
				@"DIMODPUPILSIZE1='$DIMODPUPILSIZE1'," + 
				@"DIMODPUPILSIZE2='$DIMODPUPILSIZE2'," + 
				@"DIMODPUPILREACTIVITY='$DIMODPUPILREACTIVITY'," + 
				@"DIMOSPUPILSIZE1='$DIMOSPUPILSIZE1'," + 
				@"DIMOSPUPILSIZE2='$DIMOSPUPILSIZE2'," + 
				@"DIMOSPUPILREACTIVITY='$DIMOSPUPILREACTIVITY'," + 
				@"PUPIL_COMMENTS='$PUPIL_COMMENTS'," + 
				@"ODVFCONFRONTATION1='$ODVFCONFRONTATION1'," + 
				@"ODVFCONFRONTATION2='$ODVFCONFRONTATION2'," + 
				@"ODVFCONFRONTATION3='$ODVFCONFRONTATION3'," + 
				@"ODVFCONFRONTATION4='$ODVFCONFRONTATION4'," + 
				@"ODVFCONFRONTATION5='$ODVFCONFRONTATION5'," + 
				@"OSVFCONFRONTATION1='$OSVFCONFRONTATION1'," + 
				@"OSVFCONFRONTATION2='$OSVFCONFRONTATION2'," + 
				@"OSVFCONFRONTATION3='$OSVFCONFRONTATION3'," + 
				@"OSVFCONFRONTATION4='$OSVFCONFRONTATION4'," + 
				@"OSVFCONFRONTATION5='$OSVFCONFRONTATION5'," + 
				@"ODDISC='$ODDISC'," + 
				@"OSDISC='$OSDISC'," + 
				@"ODCUP='$ODCUP'," + 
				@"OSCUP='$OSCUP'," + 
				@"ODMACULA='$ODMACULA'," + 
				@"OSMACULA='$OSMACULA'," + 
				@"ODVESSELS='$ODVESSELS'," + 
				@"OSVESSELS='$OSVESSELS'," + 
				@"ODPERIPH='$ODPERIPH'," + 
				@"OSPERIPH='$OSPERIPH'," + 
				@"ODCMT='$ODCMT'," + 
				@"OSCMT='$OSCMT'," + 
				@"RETINA_COMMENTS='$RETINA_COMMENTS'," + 
				@"IMP='$IMP'," + 
				@"PLAN='$PLAN'," + 
				@"Technician='$Technician'," + 
				@"Doctor='$Doctor'," + 
				@"Resource='$Resource'," + 
				@"LOCKED='$LOCKED'," + 
				@"LOCKEDDATE='$LOCKEDDATE'," + 
				@"LOCKEDBY='$LOCKEDBY'," + 
				@"FINISHED='$FINISHED'" + 
				
				"WHERE id = '$id'";

		$result = $this->database->Update($sql);
		$this->debug->Show(Debug::DEBUG, "form_eye_mag::Update return: $result");

		return $result;
	}
}
?>
